name: Deploy Support Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy Docker image
        env:
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
          SUPPORT_GROUP: ${{ secrets.SUPPORT_GROUP }}
        run: |
          mkdir ~/ciao