name: Deploy Support Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create data directory if not exists
        run: |
          sudo mkdir -p /opt/rustbusters-bot/data
          sudo chmod 777 /opt/rustbusters-bot/data

      - name: Build and deploy Docker image
        env:
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
          SUPPORT_GROUP: ${{ secrets.SUPPORT_GROUP }}
        run: |
          sudo docker build -t rustbusters-bot .
          sudo docker stop rustbusters-bot || true
          sudo docker rm rustbusters-bot || true
          sudo docker run -dt --name rustbusters-bot \
            -e TELOXIDE_TOKEN=$TELOXIDE_TOKEN \
            -e SUPPORT_GROUP=$SUPPORT_GROUP \
            -v /opt/rustbusters-bot/data:/data \
            rustbusters-bot